<a href="https://colab.research.google.com/github/minyou2675/Bigdata_SchoolProject/blob/main/linearmodel_diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split #sk에서 제공해주는 비율 나누는 함수
from sklearn.linear_model import LinearRegression #loss,쎄타 함수 내장 

import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
x, y = diabetes["data"], diabetes["target"]

In [ ]:
diabetes

{'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, b

In [ ]:
diabetes["data"]

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [ ]:
x[0] , y[0]

(array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613]),
 151.0)

In [ ]:
x[1], y[1] # 2번 열의 sex 값은 2개밖에 갖지 않는다. 0또는 1로 분류되는 범주형 값이기 때문이다

(array([-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405]),
 75.0)

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size =0.2) #데이터셋은 랜덤하게 분리된다

In [ ]:
len(x),len(train_x), len(test_x), len(train_y), len(test_y)

(442, 353, 89, 353, 89)

In [ ]:
regressor = LinearRegression ()
regressor.fit(train_x, train_y)

LinearRegression()

In [ ]:
regressor.coef_ #na값 찍히면 잘못 된 것

array([  41.58382436, -294.16869891,  551.6654909 ,  329.79589659,
       -759.10365544,  449.27449001,   73.36237702,  114.06573184,
        745.46253216,   32.5245066 ])

In [ ]:
train_pred = regressor.predict(train_x)
test_pred = regressor.predict(test_x)

In [ ]:
train_pred


array([194.65147217, 165.38807213, 136.16346895,  81.24062777,
       208.74674   , 216.61337819, 112.52823192, 142.06504178,
       171.71387789, 106.77477913, 181.06084424,  97.50694688,
       236.87160396, 174.50203097, 177.53196155, 109.56888179,
       220.75298097,  72.80267877, 253.73546863,  97.7204149 ,
        55.04192411, 213.21964932, 153.64741568, 161.55546087,
       159.17088536,  82.85603676,  84.76969655, 193.74481385,
       170.81774078,  92.88403578,  72.905816  , 210.26045118,
       112.88698262, 213.05622128, 170.97120085, 162.14333341,
       156.78931386, 117.7302275 ,  80.49852196, 143.42280437,
       187.99387374, 149.13018053, 100.53907737, 244.18766145,
       124.98046541, 222.17565479, 174.8817327 , 229.52906995,
        64.80075045, 193.46545908,  57.6026652 ,  94.53304641,
       160.90690254, 112.86955742, 115.27620382, 117.06193078,
       181.94780308,  84.25003767, 236.45689493, 171.65428495,
       109.75555533, 220.23593239, 170.88777338,  67.34

In [ ]:
test_pred

array([164.73510406, 232.38020385,  74.9376327 ,  76.24391257,
       247.84122807,  57.56821789, 262.92064647, 182.57183255,
        35.35271958, 133.45151877, 188.18996514, 164.32278675,
       171.80283737, 165.07972353,  61.30304327,  98.72243695,
       239.09405261, 156.33218368, 158.3246891 , 195.64984893,
       170.30051339, 162.90714463,  86.77516694, 164.12222614,
       157.21573098, 113.51771675, 159.86794515,  90.54165834,
       190.3442247 , 165.27903827, 122.32618074, 179.48406825,
        65.27405969,  99.10800541, 148.87930117, 138.79122376,
       289.98399606, 150.61960509, 181.83954603, 181.27399128,
       296.52821972, 171.81005672, 109.92118754, 188.7311744 ,
       139.43892231,  73.65362032, 167.5580768 , 120.44925763,
       181.55041804, 179.15377918, 150.74096039, 249.85859062,
       144.378809  , 243.87722173, 120.23157176, 128.18531364,
       121.8052208 , 131.56279108,  95.01917677, 154.14454965,
       102.27517946, 240.70613594, 133.5386212 , 217.99

In [ ]:
print(train_pred[1],train_y[1])

165.38807212834698 196.0


In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
train_mse = mean_squared_error(train_pred, train_y)
test_mse = mean_squared_error(test_pred, test_y)
print(train_mse, test_mse) 

2845.8039826845193 3015.440716789333
