<a href="https://colab.research.google.com/github/minyou2675/Bigdata_SchoolProject/blob/main/%EC%98%81%ED%99%94%EC%B6%94%EC%B2%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive 
from google.colab import files

files.upload()

Saving movie_recommendation.zip to movie_recommendation.zip


{'movie_recommendation.zip': b'PK\x03\x04-\x00\x00\x00\x08\x00\x9aPHO\x9a\x1a\x11h\xff\xff\xff\xff\xff\xff\xff\xff\n\x00\x14\x00README.txt\x01\x00\x10\x00\x96 \x00\x00\x00\x00\x00\x00\xdb\x0c\x00\x00\x00\x00\x00\x00\xbdY[r\x1b\xc7\x15\xfd\xc7*:\xfe1\xa1\x02\xc0\x87\xf5.\x87\x15\x15e\xd9\xb4%\xc7%R\xf1\x87+\x156f\x1a@\x873\xd3\xa3\xee\x1eB\xc8W\xf6\x90Ud\x1d\xd9IV\x92sn\xf7\x0c@\n\x92\xa5r\xca,\x950\x18Lw\xdf\xc7\xb9\xe7>\xe6\xa2\xabk\xed7\xa3?\xa6\xbf\xd1\xe8re\x83*u\xd4\xc1DuPW\xd3JG\x13\xe24\xd4\xba\xaa\xc6\xaa4\xa1\xf0vn\x82z0\rQ{\xe5u\xb4\xcdR\xe9\xa6T\x0bo\xcc4\x9awQE\xbd\\\xca\xdd"\xda\x1b\x1b7\xf8\xc9\xd5\xea\x97W\xee\xc6\x9a\x97\xa6\t\x7f=X\xc5\xd8>=<\xacy\xa7\xc2\x9d\x99\xf3\xcb\xf1Di%w\x947\x85\xabk\xd3@\x10\xeb\x1a\x15\x8c\xbf\xb1\x85\x99\xa9\xf3\xa8\n\xd7Dm\x9b\xa0\x8e\x8f\x8e\x1e\x7f\xf50\x0b\x10D\x82\xaf\x1e>\xfe\x8a\x87+\xdd\xb6\x95-d1~)\xbc\x0bA=yt\xff$m\x1ff\xeare\x82\x11=\xd5\xdax\xa3\no\xa0g\xa9\xe6\x1b\xf5\xf0\xf8Hu81\xa8\xb9\x89kc\x1a\xf5J\xfbb\xa5N\x9eL\xd4\xf1\x9

In [ ]:
%cd /content
!unzip '/content/movie_recommendation.zip'

/content
Archive:  /content/movie_recommendation.zip
  inflating: README.txt              
  inflating: links.csv               
  inflating: movies.csv              
  inflating: ratings.csv             
  inflating: tags.csv                


In [ ]:
import pandas as pd
import numpy as np

movies = pd.read_csv('/content/links.csv')
movies.head()

movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
links = pd.read_csv('/content/links.csv')
ratings = pd.read_csv('/content/ratings.csv')
tags = pd.read_csv('/content/tags.csv')

In [ ]:
links.head()

movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
tags.head()

userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [ ]:
df1 = pd.merge(ratings,movies,on='movieId',how='inner')
df1.head()

userId  movieId  rating   timestamp  imdbId  tmdbId
0       1        1     4.0   964982703  114709   862.0
1       5        1     4.0   847434962  114709   862.0
2       7        1     4.5  1106635946  114709   862.0
3      15        1     2.5  1510577970  114709   862.0
4      17        1     4.5  1305696483  114709   862.0

In [ ]:
df1 = df1.drop(['imdbId','tmdbId'],axis=1)
df1.head()

userId  movieId  rating   timestamp
0       1        1     4.0   964982703
1       5        1     4.0   847434962
2       7        1     4.5  1106635946
3      15        1     2.5  1510577970
4      17        1     4.5  1305696483

In [ ]:
df1.rename(columns={'userId':'user'},inplace=True)
df1.rename(columns={'movieId':'movie'},inplace=True)
df1.head()

user  movie  rating   timestamp
0     1      1     4.0   964982703
1     5      1     4.0   847434962
2     7      1     4.5  1106635946
3    15      1     2.5  1510577970
4    17      1     4.5  1305696483

In [ ]:
X = df1.values
X[:,0]

array([  1.,   5.,   7., ..., 610., 610., 610.])

In [ ]:
n = X.shape[0]
print(n)

100836


In [ ]:
k=3

x = X[:,0]
y = X[:,1]
z = X[:,2]
centroid_x = np.random.uniform(min(x),max(x), k)
centroid_y = np.random.uniform(min(y),max(y), k)
centroid_z = np.random.uniform(min(z),max(z), k)

centroid = list(zip(centroid_x, centroid_y, centroid_z))
centroids = np.array(centroid)
print(centroids)

[[2.64120493e+02 1.22706929e+05 1.07850235e+00]
 [3.98460195e+02 9.99479753e+04 6.58407329e-01]
 [1.16068744e+02 5.09898538e+04 3.18600063e+00]]


In [ ]:
def distance(a,b):
  alen = len(a)
  sum = 0
  for aidx in range (alen):
    sum += (a[aidx] - b[aidx]) **2 #a,b의 모든 원소들의 차의 제곱을 더한다
    return sum **0.5

In [ ]:
from copy import deepcopy

points = np.array(list(zip(x,y,z)))

centroids_old = np.zeros(centroids.shape)
error = np.zeros(k)
error_old = deepcopy(error)
print(centroids_old)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#error 초기화
for i in range(3):
  error[i] = distance(centroids_old[i],centroid[i])

idx = 0
while(error.any() != 0):
  #가장 가까운 centroid point를 clustering
  for i in range(10000):
    distances = np.zeros(k)
    print(distances)


     #데이터 하나로부터 세 centroid 거리 계산/ 가장 작은 값 index 구하기! argmin 구하기
    for j in range(k):
      distances[j] = distance(points[i], centroids[j])
   
     #데이터 하나로부터 세 centroid 거리 계산/ 가장 작은 값 index 구하기! argmin 구하기

  #X

Streaming output truncated to the last 5000 lines.
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0.

In [ ]:
import torch

class Data_to_tensor:
  def __init__(self, users, movies, ratings):
    self.users = users
    self.movies = movies
    self.ratings = ratings

  def __len__(self):
    return len(self.users) 


  def __getitem__(self, item):
    user = self.users[item]
    movie = self.movies[item]
    rating = self.ratings[item] #class에서 index값 따라 불러옴 

    return { "user" : torch.tensor(user, dtype = torch.long),
             "movie": torch.tensor(movie, dtype = torch.long),
             "rating": torch.tensor(rating, dtype = torch.float),
                                   }




In [ ]:
!pip install tez 

In [ ]:

import tez
import torch.nn as nn
from sklearn import model_selection
from sklearn import metrics
from sklearn import preprocessing

class RecModel(tez.Model):
  def __init__(self, num_users, num_movies):
    super().__init__()
    self.user_embeds = nn.Embedding(num_users, 32)
    self.movie_embeds = nn.Embedding(num_movies, 32)
    self.out = nn.Linear(64,1)
    self.step_scheduler_after = 'epoch'
  
  def fetch_optimizer(self):
    opt = torch.optim.Adam(self.parameters(), lr=1e-3)
    return opt

  def fetch_scheduler(self):
      sch = torch.optim.lr_scheduler.StepLR(self.optimizer, step_size=3, gamma=0.7)
      return sch



  def monitoring_metrics(self, output, rating):
    output = output.detach().cpu().numpy()
    rating = rating.detach().cpu().numpy()
    return {'rmse':np.sqrt(metrics.mean_squared_error(output, rating))}


  def forward(self, user, movie, ratings=None):
    user_embeds = self.user_embeds(user)
    movie_embeds = self.user_embeds(movie)
    output = torch.cat([user_embeds,movie_embeds], dim=1)
    output = self.out(output)
    loss = nn.MSELoss()(output,ratings.views(-1,1 ))
    metrics = self.monitor_metrics(output, ratings.view(-1,1))
    return output, loss, metrics









In [ ]:




if __name__ == "__main__":
  def train(df):
    lbl_user = preprocessing.LabelEncoder()
    lbl_movie = preprocessing.LabelEncoder()

    df.user = lbl_user.fit_transform(df.user.values)
    df.movie = lbl_movie.fit_transform(df.movie.values)

    df_train, df_valid = model_selection.train_test_split(
        df, test_size=0.1, random_state = 42, stratify = df.rating.values
    )

    train_dataset = Data_to_tensor(users=df_train.user.values, movies=df_train.movie.values,
                                   ratings=df_train.rating.values)
    valid_dataset = Data_to_tensor(users=df_valid.user.values, movies = df_valid.movie.values,
                                   ratings=df_valid.rating.values)
    model = RecModel(num_users = len(lbl_user.classes_), num_movies=len(lbl_movie.classes_))
    model.fit(train_dataset, valid_dataset, train_bs=1024, valid_bs=1024, fp16=True)
  train(df1)


